import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as path from "path";

interface AuthResourcesProps {
  usersTable?: cdk.aws_dynamodb.Table;
}

export class AuthResources extends Construct {
  public readonly userPool: cdk.aws_cognito.UserPool;
  public readonly userPoolClient: cdk.aws_cognito.UserPoolClient;
  public readonly userPoolDomain: cdk.aws_cognito.UserPoolDomain;
  public readonly identityPool: cdk.aws_cognito.CfnIdentityPool;
  public readonly appleAuthApi: cdk.aws_apigateway.RestApi;

  constructor(scope: Construct, id: string, props?: AuthResourcesProps) {
    super(scope, id);

    this.userPool = new cdk.aws_cognito.UserPool(this, "UserPool", {
      signInAliases: {
        email: true,
        username: true,
      },
      selfSignUpEnabled: true,
      autoVerify: { email: true },
      standardAttributes: {
        email: {
          required: true,
          mutable: true,
        },
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // Create a domain for the User Pool
    const userPoolDomain = new cdk.aws_cognito.UserPoolDomain(
      this,
      "UserPoolDomain",
      {
        userPool: this.userPool,
        cognitoDomain: {
          // TODO: this shouldnt be hardcoded? not sure if it can be autogenerated or if it should just be the app name or something
          domainPrefix: "expo-auth-pp7xcj",
        },
      }
    );

    // Google OAuth provider
    const googleProvider = new cdk.aws_cognito.UserPoolIdentityProviderGoogle(
      this,
      "GoogleProvider",
      {
        userPool: this.userPool,
        clientId: process.env.GOOGLE_CLIENT_ID!,
        clientSecretValue: cdk.SecretValue.unsafePlainText(
          process.env.GOOGLE_CLIENT_SECRET!
        ),
        scopes: ["email", "openid", "profile"],
        attributeMapping: {
          email: cdk.aws_cognito.ProviderAttribute.GOOGLE_EMAIL,
          givenName: cdk.aws_cognito.ProviderAttribute.GOOGLE_GIVEN_NAME,
          familyName: cdk.aws_cognito.ProviderAttribute.GOOGLE_FAMILY_NAME,
        },
      }
    );

    // Apple OAuth provider
    const appleProvider = new cdk.aws_cognito.UserPoolIdentityProviderApple(
      this,
      "AppleProvider",
      {
        userPool: this.userPool,
        clientId: process.env.APPLE_CLIENT_ID!,
        teamId: process.env.APPLE_TEAM_ID!,
        keyId: process.env.APPLE_KEY_ID!,
        privateKeyValue: cdk.SecretValue.unsafePlainText(
          process.env.APPLE_PRIVATE_KEY!
        ),
        scopes: ["email", "name"],
        attributeMapping: {
          email: cdk.aws_cognito.ProviderAttribute.APPLE_EMAIL,
          givenName: cdk.aws_cognito.ProviderAttribute.APPLE_FIRST_NAME,
          familyName: cdk.aws_cognito.ProviderAttribute.APPLE_LAST_NAME,
        },
      }
    );

    this.userPoolClient = new cdk.aws_cognito.UserPoolClient(
      this,
      "UserPoolClient",
      {
        userPool: this.userPool,
        authFlows: {
          adminUserPassword: true,
          userPassword: true,
          userSrp: true,
          custom: true,
        },
        oAuth: {
          flows: {
            authorizationCodeGrant: true,
          },
          scopes: [
            cdk.aws_cognito.OAuthScope.EMAIL,
            cdk.aws_cognito.OAuthScope.OPENID,
            cdk.aws_cognito.OAuthScope.PROFILE,
          ],
          callbackUrls: ["exp://localhost:8081/--/"],
          logoutUrls: ["exp://localhost:8081/--/"],
        },
        supportedIdentityProviders: [
          cdk.aws_cognito.UserPoolClientIdentityProvider.COGNITO,
          cdk.aws_cognito.UserPoolClientIdentityProvider.GOOGLE,
          cdk.aws_cognito.UserPoolClientIdentityProvider.APPLE,
        ],
        refreshTokenValidity: cdk.Duration.days(365),
      }
    );

    this.userPoolClient.node.addDependency(googleProvider);
    this.userPoolClient.node.addDependency(appleProvider);

    this.userPoolDomain = userPoolDomain;

    this.userPool.addGroup("AdminsGroup", {
      groupName: `${this.userPool.userPoolId}_Admin`,
      description: "Administrators group",
      precedence: 0,
    });

    this.userPool.addGroup("EmailGroup", {
      groupName: `${this.userPool.userPoolId}_Email`,
      description: "Users group (signup with email)",
    });

    // Create Cognito Identity Pool for native Apple Sign In
    this.identityPool = new cdk.aws_cognito.CfnIdentityPool(
      this,
      "IdentityPool",
      {
        allowUnauthenticatedIdentities: false,
        supportedLoginProviders: {
          // TODO: i think bundle id is correct, try removing client id
          "appleid.apple.com":
            process.env.APPLE_BUNDLE_ID || process.env.APPLE_CLIENT_ID!,
        },
      }
    );

    // TODO: maybe move this apple related auth stuff to another construct? (file) not sure

    // Create IAM role for authenticated users
    const authenticatedRole = new cdk.aws_iam.Role(this, "AuthenticatedRole", {
      assumedBy: new cdk.aws_iam.FederatedPrincipal(
        "cognito-identity.amazonaws.com",
        {
          StringEquals: {
            "cognito-identity.amazonaws.com:aud": this.identityPool.ref,
          },
          "ForAnyValue:StringLike": {
            "cognito-identity.amazonaws.com:amr": "authenticated",
          },
        },
        "sts:AssumeRoleWithWebIdentity"
      ),
      managedPolicies: [
        cdk.aws_iam.ManagedPolicy.fromAwsManagedPolicyName(
          "AmazonCognitoPowerUser"
        ),
      ],
    });

    // Attach the role to the identity pool
    new cdk.aws_cognito.CfnIdentityPoolRoleAttachment(
      this,
      "IdentityPoolRoleAttachment",
      {
        identityPoolId: this.identityPool.ref,
        roles: {
          authenticated: authenticatedRole.roleArn,
        },
      }
    );

    // Create Lambda function for Apple authentication (deploy built JS from lambda/dist)
    const appleAuthLambda = new cdk.aws_lambda.Function(
      this,
      "AppleAuthLambda",
      {
        runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
        handler: "apple-auth.handler",
        code: cdk.aws_lambda.Code.fromAsset(
          path.join(__dirname, "../../lambda/dist"),
          {
            // exclude source files - include package and node_modules so runtime deps are packaged
            exclude: ["**/*.ts"],
          }
        ),
        environment: {
          IDENTITY_POOL_ID: this.identityPool.ref,
          APPLE_CLIENT_ID: process.env.APPLE_CLIENT_ID!,
          // Bundle ID used by the native app (e.g. com.gusflus.expoapp)
          APPLE_BUNDLE_ID: process.env.APPLE_BUNDLE_ID!,
          // Also include the service ID explicitly so the lambda has both
          // TODO: should only need one
          APPLE_SERVICE_ID:
            process.env.APPLE_SERVICE_ID || process.env.APPLE_CLIENT_ID!,
          // Cognito User Pool id to persist users
          USER_POOL_ID: this.userPool.userPoolId,
          // Name of the identity provider configured on the User Pool (example: SignInWithApple)
          // TODO: should only need one
          APPLE_PROVIDER_NAME:
            process.env.APPLE_PROVIDER_NAME || "SignInWithApple",
          // Optional DynamoDB Users table name injected by stack
          ...(props?.usersTable
            ? { USERS_TABLE_NAME: props.usersTable.tableName }
            : {}),
        },
        timeout: cdk.Duration.seconds(30),
      }
    );

    // Grant permissions to the Lambda
    appleAuthLambda.addToRolePolicy(
      new cdk.aws_iam.PolicyStatement({
        effect: cdk.aws_iam.Effect.ALLOW,
        actions: [
          "cognito-identity:GetId",
          "cognito-identity:GetCredentialsForIdentity",
        ],
        resources: ["*"],
      })
    );

    // Allow managing users in the User Pool (create/link users)
    appleAuthLambda.addToRolePolicy(
      new cdk.aws_iam.PolicyStatement({
        effect: cdk.aws_iam.Effect.ALLOW,
        actions: [
          "cognito-idp:ListUsers",
          "cognito-idp:AdminCreateUser",
          "cognito-idp:AdminLinkProviderForUser",
          "cognito-idp:AdminGetUser",
          "cognito-idp:AdminUpdateUserAttributes",
        ],
        resources: [
          `arn:aws:cognito-idp:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:userpool/*`,
        ],
      })
    );

    // Create API Gateway
    this.appleAuthApi = new cdk.aws_apigateway.RestApi(this, "AppleAuthApi", {
      restApiName: "Apple Auth Service",
      description: "API for native Apple Sign In authentication",
      defaultCorsPreflightOptions: {
        allowOrigins: cdk.aws_apigateway.Cors.ALL_ORIGINS,
        allowMethods: cdk.aws_apigateway.Cors.ALL_METHODS,
        allowHeaders: ["Content-Type", "Authorization"],
      },
    });

    const appleAuthIntegration = new cdk.aws_apigateway.LambdaIntegration(
      appleAuthLambda
    );
    this.appleAuthApi.root
      .addResource("apple-auth")
      .addMethod("POST", appleAuthIntegration);

    // Create Lambda function for checking whether an email already exists in the user pool
    const checkEmailLambda = new cdk.aws_lambda.Function(
      this,
      "CheckEmailLambda",
      {
        runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
        handler: "check-email.handler",
        code: cdk.aws_lambda.Code.fromAsset(
          path.join(__dirname, "../../lambda/dist"),
          {
            exclude: ["**/*.ts"],
          }
        ),
        environment: {
          USER_POOL_ID: this.userPool.userPoolId,
        },
        timeout: cdk.Duration.seconds(30),
      }
    );

    // Permissions for the check email Lambda - only needs to list/get users
    checkEmailLambda.addToRolePolicy(
      new cdk.aws_iam.PolicyStatement({
        effect: cdk.aws_iam.Effect.ALLOW,
        actions: ["cognito-idp:ListUsers", "cognito-idp:AdminGetUser"],
        resources: [
          `arn:aws:cognito-idp:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:userpool/*`,
        ],
      })
    );

    const checkEmailIntegration = new cdk.aws_apigateway.LambdaIntegration(
      checkEmailLambda
    );
    this.appleAuthApi.root
      .addResource("check-email")
      .addMethod("POST", checkEmailIntegration);

    // If a DynamoDB users table was provided, wire up user GET/POST endpoints
    if (props?.usersTable) {
      // Grant the apple auth lambda read/write access so it can persist initial user info
      props.usersTable.grantReadWriteData(appleAuthLambda);

      // Lambda to get user data from DynamoDB
      const getUserLambda = new cdk.aws_lambda.Function(this, "GetUserLambda", {
        runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
        handler: "get-user.handler",
        code: cdk.aws_lambda.Code.fromAsset(
          path.join(__dirname, "../../lambda/dist"),
          {
            exclude: ["**/*.ts"],
          }
        ),
        environment: {
          USERS_TABLE_NAME: props.usersTable.tableName,
        },
        timeout: cdk.Duration.seconds(10),
      });

      props.usersTable.grantReadData(getUserLambda);

      const getUserIntegration = new cdk.aws_apigateway.LambdaIntegration(
        getUserLambda
      );
      this.appleAuthApi.root
        .addResource("user")
        .addMethod("GET", getUserIntegration);

      // Lambda to update user data (merge missing attributes)
      const updateUserLambda = new cdk.aws_lambda.Function(
        this,
        "UpdateUserLambda",
        {
          runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
          handler: "update-user.handler",
          code: cdk.aws_lambda.Code.fromAsset(
            path.join(__dirname, "../../lambda/dist"),
            {
              exclude: ["**/*.ts"],
            }
          ),
          environment: {
            USERS_TABLE_NAME: props.usersTable.tableName,
            USER_POOL_ID: this.userPool.userPoolId,
          },
          timeout: cdk.Duration.seconds(10),
        }
      );

      props.usersTable.grantWriteData(updateUserLambda);

      // The update lambda may need to write back to Cognito attributes
      updateUserLambda.addToRolePolicy(
        new cdk.aws_iam.PolicyStatement({
          effect: cdk.aws_iam.Effect.ALLOW,
          actions: ["cognito-idp:AdminUpdateUserAttributes"],
          resources: [
            `arn:aws:cognito-idp:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:userpool/*`,
          ],
        })
      );

      const updateUserIntegration = new cdk.aws_apigateway.LambdaIntegration(
        updateUserLambda
      );
      this.appleAuthApi.root
        .getResource("user")
        ?.addMethod("POST", updateUserIntegration);

      // Post-confirmation trigger to persist users that sign up with Cognito flows
      const postConfirmLambda = new cdk.aws_lambda.Function(
        this,
        "PostConfirmLambda",
        {
          runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
          handler: "post-confirm.handler",
          code: cdk.aws_lambda.Code.fromAsset(
            path.join(__dirname, "../../lambda/dist"),
            {
              exclude: ["**/*.ts"],
            }
          ),
          environment: {
            USERS_TABLE_NAME: props.usersTable.tableName,
          },
          timeout: cdk.Duration.seconds(10),
        }
      );

      props.usersTable.grantReadWriteData(postConfirmLambda);
      postConfirmLambda.addToRolePolicy(
        new cdk.aws_iam.PolicyStatement({
          effect: cdk.aws_iam.Effect.ALLOW,
          actions: ["cognito-idp:AdminGetUser"],
          resources: [
            `arn:aws:cognito-idp:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:userpool/*`,
          ],
        })
      );

      // Attach the post confirmation trigger to the User Pool
      this.userPool.addTrigger(
        cdk.aws_cognito.UserPoolOperation.POST_CONFIRMATION,
        postConfirmLambda
      );
    }

    // Create Lambda for customizing Cognito messages (signup codes, forgot password, etc.)
    const customMessageLambda = new cdk.aws_lambda.Function(
      this,
      "CustomMessageLambda",
      {
        runtime: cdk.aws_lambda.Runtime.NODEJS_20_X,
        handler: "custom-message.handler",
        code: cdk.aws_lambda.Code.fromAsset(
          path.join(__dirname, "../../lambda/dist"),
          { exclude: ["**/*.ts"] }
        ),
        timeout: cdk.Duration.seconds(10),
      }
    );

    // Attach the custom message trigger to the User Pool
    this.userPool.addTrigger(
      cdk.aws_cognito.UserPoolOperation.CUSTOM_MESSAGE,
      customMessageLambda
    );
  }
}
